export component Window5 inherits Rectangle {
    in property <bool> window5_active: false;
    in property <int> x_translation: 0;
    in property <int> y_translation: 0;
    in property <int> x_scale: 0;
    in property <int> y_scale: 0;
    window := Rectangle {
        x: 100px + (x_translation * 1px);
        y: 100px + (y_translation * 1px); 

        background: #000000dd;
        border-radius: 6px;
        border-width: 5px;
        border-color: #008080;
        width: 500px + (x_scale * 1px);
        height: 500px + (y_scale * 1px);
        visible: root.window5_active;
    }
    label := Text {
        x: 100px + (x_translation * 1px);
        y: 90px + (y_translation * 1px);
        width: 110px;

        text: "Terminal";
        color: #00b3b3;
        font-size: 11px + (x_scale * 1px);
        horizontal-alignment: center;
        visible: root.window5_active;
    }
}
