component QSIcon inherits Rectangle {
    in property <bool> selected: false;
    width: 30px;
    height: 30px;
    border-radius: 5px;
    background: selected ? #00b3b3 : #008080;
}

export component QuickSettings inherits Rectangle {
    in property <bool> active: false;
    in property <bool> pill-active: false;
    in property <int> selection: 0;

    hidden_pill := Rectangle {
        x: parent.width - 200px;
        y: 23px;

        width: 200px;
        height: 15px;
        border-width: root.pill-active ? 2px : 0px;
        border-radius: 10px;
        border-color: #1a1a1a;

        background: #1a1a1a;
        visible: !root.active;
    }

    panel := Rectangle {
        x: parent.width - 200px;
        y: 28px;

        width: 200px;
        height: 100px;
        border-radius: 10px;
        border-width: root.active ? 2px : 0px;
        border-color: #00b3b3;

        background: #1a1a1a;
        visible: root.active;
        GridLayout {
            padding: 15px;
            spacing: 5px;

            for idx in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] : QSIcon {
                row: idx / 5;
                col: Math.mod(idx, 5);
                selected: root.selection == idx;
            }
        }
    }

    label := Text {
        x: parent.width - 150px;
        y: 130px;
        width: 100px;

        text: "QUICK SETTINGS";
        color: #00b3b3;
        font-size: 11px;
        horizontal-alignment: center;
        visible: root.active;
    }
}
